export enum CurrencyCodes {
  USD = 'USD',
  JPY = 'JPY',
  BGN = 'BGN',
  CZK = 'CZK',
  DKK = 'DKK',
  GBP = 'GBP',
  HUF = 'HUF',
  PLN = 'PLN',
  RON = 'RON',
  SEK = 'SEK',
  CHF = 'CHF',
  ISK = 'ISK',
  NOK = 'NOK',
  HRK = 'HRK',
  RUB = 'RUB',
  TRY = 'TRY',
  AUD = 'AUD',
  BRL = 'BRL',
  CAD = 'CAD',
  CNY = 'CNY',
  HKD = 'HKD',
  IDR = 'IDR',
  ILS = 'ILS',
  INR = 'INR',
  KRW = 'KRW',
  MXN = 'MXN',
  MYR = 'MYR',
  NZD = 'NZD',
  PHP = 'PHP',
  SGD = 'SGD',
  THB = 'THB',
  ZAR = 'ZAR',
}

export const CurrencyNames = {
  [CurrencyCodes.USD]: 'US Dolars',
  [CurrencyCodes.JPY]: 'Yen',
  [CurrencyCodes.BGN]: '',
  [CurrencyCodes.CZK]: '',
  [CurrencyCodes.DKK]: 'Krona',
  [CurrencyCodes.GBP]: 'Sterling',
  [CurrencyCodes.HUF]: '',
  [CurrencyCodes.PLN]: '',
  [CurrencyCodes.RON]: '',
  [CurrencyCodes.SEK]: '',
  [CurrencyCodes.CHF]: '',
  [CurrencyCodes.ISK]: '',
  [CurrencyCodes.NOK]: '',
  [CurrencyCodes.HRK]: '',
  [CurrencyCodes.RUB]: 'Rubles',
  [CurrencyCodes.TRY]: '',
  [CurrencyCodes.AUD]: '',
  [CurrencyCodes.BRL]: '',
  [CurrencyCodes.CAD]: '',
  [CurrencyCodes.CNY]: '',
  [CurrencyCodes.HKD]: 'HK Dollars',
  [CurrencyCodes.IDR]: '',
  [CurrencyCodes.ILS]: '',
  [CurrencyCodes.INR]: '',
  [CurrencyCodes.KRW]: '',
  [CurrencyCodes.MXN]: '',
  [CurrencyCodes.MYR]: '',
  [CurrencyCodes.NZD]: 'NZ Dollars',
  [CurrencyCodes.PHP]: '',
  [CurrencyCodes.SGD]: '',
  [CurrencyCodes.THB]: '',
  [CurrencyCodes.ZAR]: '',
}
