export const CurrencyNames: {[k: string]: string} = {
  HOT: 'Hots',
  DOG: 'Dogs',
  USD: 'United States Dolars',
  JPY: 'Yen',
  BGN: '',
  CZK: '',
  DKK: 'Krona',
  GBP: 'GB Pound Sterling',
  HUF: '',
  PLN: '',
  RON: '',
  SEK: '',
  CHF: '',
  ISK: '',
  NOK: '',
  HRK: '',
  RUB: 'Rubles',
  TRY: '',
  AUD: '',
  BRL: '',
  CAD: '',
  CNY: '',
  HKD: 'Hong Kong Dollars',
  IDR: '',
  ILS: '',
  INR: '',
  KRW: '',
  MXN: '',
  MYR: '',
  NZD: 'New Zealand Dollars',
  PHP: '',
  SGD: '',
  THB: '',
  ZAR: '',
}
